name: Metrics
on:
  schedule: [{cron: "0 1 * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          config_timezone: Europe/Paris
          plugin_music: no
          plugin_lines: yes
          plugin_traffic: yes
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
          plugin_languages: yes
          plugin_isocalendar: yes
          plugin_pagespeed: yes
          plugin_pagespeed_detailed: yes  
          plugin_pagespeed_screenshot: no  
          plugin_pagespeed_url: shockedplot7560.tk          
